---
- name: 判断nginx是否已经安装
  stat: path={{ nginx_basedir }}
  register: reg_nginx
- name: copy nginx
  unarchive: src=nginx-{{nginx_version}}.tar.gz dest=/usr/local
  when: not reg_nginx.stat.exists

- name: 安装nginx依赖包[zlib-devel pcre-devel openssl-devel]
  yum: name={{ item }} state=latest
  with_items:
  - zlib-devel
  - pcre-devel
  - openssl-devel
  - gcc
  when: not reg_nginx.stat.exists

- name: 上传nginx安装脚本
  template: src=install.sh.j2 dest=/tmp/install.sh owner=root group=root mode=0777
  when: not reg_nginx.stat.exists

- name: 安装nginx
  shell:  /bin/bash /tmp/install.sh
  when: not reg_nginx.stat.exists

- name: 上传nginx.conf
  template:  src=nginx.conf.j2  dest={{nginx_basedir}}/conf/nginx.conf backup=yes
  notify: start_nginx
  when: not reg_nginx.stat.exists



