---
nginx_servers: 
  - name: center.cprs.uat
    listenPort: 80
    useBackend: true
    backends_name: eclp
    backends:
      - ip_address: 192.168.100.101
        port: 8080
        parameters: max_fails=3 fail_timeout=30s
      - ip_address: 192.168.100.102
        port: 8080
        parameters: max_fails=3 fail_timeout=30s

  - name: uc.cprs.uat
    listenPort: 80
    useBackend: true
    backends_name: uc-webapp
    backends:
      - ip_address: 192.168.100.102
        port: 8081
        parameters: max_fails=3 fail_timeout=30s
      - ip_address: 192.168.100.101
        port: 8081
        parameters: max_fails=3 fail_timeout=30s

