---
nginx_version:  1.14.2
nginx_user: root
nginx_port: 80
nginx_basedir: /usr/local/nginx
nginx_worker_processes: auto
nginx_error_log: logs/error.log
nginx_pid_path: logs/nginx.pid
worker_connections: 50000

nginx_servers: 
  - name: center.cprs.uat
    listenPort: 80
    useBackend: true
    backends_name: eclp
    backends:
      - ip_address: 192.168.100.101
        port: 8080
        parameters: max_fails=3 fail_timeout=30s
      - ip_address: 192.168.100.102
        port: 8080
        parameters: max_fails=3 fail_timeout=30s

  - name: uc.cprs.uat
    listenPort: 80
    useBackend: false
    backends_name: none

