---
# play_book for  basic

 - hosts: all
   remote_user: root
   become: yes
   become_method: sudo
   gather_facts: yes
   roles:
     - initialize

 - hosts: ntp_server
   remote_user: root
   become: yes
   become_method: sudo
   gather_facts: no
   roles:
     - ntp_server

 - hosts: ntp_client
   remote_user: root
   become: yes
   become_method: sudo
   gather_facts: no
   roles:
     - ntp_client

 - hosts: nginx
   remote_user: root
   become: yes
   become_method: sudo
   gather_facts: no
   roles:
     - nginx
 - hosts: keepalived-master
   remote_user: root
   become: yes
   become_method: sudo
   gather_facts: yes
   roles:
     - { role: keepalived, vip: 192.168.100.200, keepalived_node: master  }

 - hosts: keepalived-slave
   remote_user: root
   become: yes
   become_method: sudo
   gather_facts: yes
   roles:
     - { role: keepalived, vip: 192.168.100.200, keepalived_node: slave  }

 - hosts: nfs-client
   remote_user: root
   become: yes
   become_method: sudo
   gather_facts: yes 
   roles:
     - nfs-client

 - hosts: nfs-server
   remote_user: root
   become: yes
   become_method: sudo
   gather_facts: yes 
   roles:
     - nfs-server


 - hosts: memcached
   remote_user: root
   become: yes
   become_method: sudo
   gather_facts: no
   roles:
     - memcached

 - hosts: redis
   remote_user: root
   become: yes
   become_method: sudo
   gather_facts: no
   roles:
     - redis

 - hosts: all
   remote_user: root
   become: yes
   become_method: sudo
   gather_facts: no
   roles:
     - oracle-java

