---
- hosts: localhost
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - ntp_server 

- hosts: other
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - ntp_client 