---
- name: "pkg: 安装常用yum模块"
  yum:  name={{ item }} state=latest
  with_items: "{{ installed_package }}"

  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 6)
  tags: [initialize,pkg]

  