---
- name: "selinux: 安装libselinux-python"
  yum:  name=libselinux-python  state=present
  when : ansible_os_family == "RedHat" 
  tags: [initialize,selinux]

- name: "selinux: disable selinux"
  selinux: state=disabled
  when : ansible_os_family == "RedHat" 
  tags: [initialize,selinux]