---
- name: check zoneinfo
  stat: path=/usr/share/zoneinfo/{{ zonename | default('Asia/Shanghai') }}
  register: target_zoneinfo
  tags: [timezone]

- name: skip if zoneinfo is not found.
  fail: msg="{{ zonename | default('Asia/Shanghai')}} is not found"
  when: target_zoneinfo.stat.md5 is not defined
  tags: [timezone]

- name: check localtime
  stat: path=/etc/localtime follow=yes
  register: target_localtime
  tags: [timezone]

- name: symlink /etc/localtime
  file:
    src:   /usr/share/zoneinfo/{{ zonename | default('Asia/Shanghai') }}
    dest:  /etc/localtime
    state: link
    force: yes
  when:         (target_zoneinfo.stat.md5 != target_localtime.stat.md5)
  changed_when: (target_zoneinfo.stat.md5 != target_localtime.stat.md5)
  tags: [timezone]

- name: /etc/sysconfig/clock
  lineinfile:
    dest=/etc/sysconfig/clock
    regexp="^ZONE"
    line='ZONE="{{ zonename | default('Asia/Shanghai') }}"'
  register:     is_sysconfig_clock
  when: ( ansible_distribution_major_version != "7" )
  changed_when: is_sysconfig_clock.changed is defined and is_sysconfig_clock.changed
  tags: [timezone]