---
## 安装参数
memcached_version:  1.4.21
memcached_basedir: /usr/local/memcached

## 配置参数
mem_user: memcached
mem_port: 11212
max_conn: 1024
cache_size: 512
fs_file_max: 756024
pid_file_path: /var/run/memcached

