---
  - name: install keeepalived package
    yum : name=keepalived  state=latest
  - name: copy script to remote
    copy: src=nginx_pid.sh  dest=/usr/local/scripts/nginx_pid.sh
  - name: configure keepalived on master
    template: src=keepalived-master.conf dest=/etc/keepalived/keepalived.conf
    when: "host='keepalived-master'"
    notify: restart keepalived
  - name: configure keepalived on slave
    template: src=keepalived-slave.conf dest=/etc/keepalived/keepalived.conf
    when: "host='keepalived-slave'"
    notify: restart keepalived
  - name: start keepalived service
    service: name=keepalived state=started enabled=yes
