---
- name: "安装更新ntp和tzdata"
  yum:  name={{ item }} state=present
  with_items:
    - ntp
    - tzdata
  when : (ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 6)
  tags: [ntp_server]

- name: "设置timezone"
  timezone: name="{{ntp_timezone}}"
  tags: [ntp_server]

- name: "确认ntp服务关闭"
  service:
    name: ntpd
    state: stopped
  tags: [ntp_server]

- name: "ntpdate 同步时钟源"
  command: "ntpdate {{ item }} "
  with_items: "{{ ntp_parent_servers }}"
  tags: [ntp_server]

- name: "确认ntp服务启动"
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: [ntp_server]
  
- name: "配置ntp服务"
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntpd
  tags: [ntp_server]